parserOptions:
  ecmaVersion: 2018
  sourceType: 'module'

env:
  es6: true
  commonjs: true
  browser: true

extends: 'htmlacademy/es6'

rules:
  quotes:
    - error
    - single
  max-nested-callbacks:
    - error
    - 4

